import { QuartzTransformerPlugin } from "../types"

const foamBlockRegex = /\n\[\/\/begin\]: # "Autogenerated link references"[\s\S]*?\[\/\/end\]: # "Autogenerated link references"\n?/g

export const StripFoamLinks: QuartzTransformerPlugin = () => {
  return {
    name: "StripFoamLinks",
    textTransform(_ctx, src) {
      return src.replace(foamBlockRegex, "")
    },
  }
}
